apiVersion: v1
kind: Pod
metadata:
    name: microservice-seguridad-pod
    labels:
        app: microservice-seguridad
        type: microservice
spec:
    containers:
        - name: microservice-seguridad-app
          image: isaga01/serviciosapiseguridad
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__ConexionDB
              value: Server=mssql-service;Database=Seguridad;User=sa;Password=123456