apiVersion: v1
kind: Pod
metadata:
    name: microservice-libreria-pod
    labels:
        app: microservice-libreria
        type: microservice
spec:
    containers:
        - name: microservice-libreria-app
          image: isaga01/serviciosapilibreria
          ports:
            - containerPort: 80