apiVersion: v1
kind: Service
metadata:
    name: microservice-libreria-service
    labels:
        name: microservice-libreria-service
        app: microservice
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30008
    selector:
        app: microservice-libreria
        type: microservice