apiVersion: v1
kind: Service
metadata:
    name: microservice-seguridad-service
    labels:
        name: microservice-seguridad-service
        app: microservice
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30009
    selector:
        app: microservice-seguridad
        type: microservice