apiVersion: v1
kind: Service
metadata:
    name: mongo-service
    labels:
        nmae: mongo-service
        app: database
spec:
    type: LoadBalancer
    ports:
        - port: 27017
          targetPort: 27017
    selector:
        app: microservice-libreria
        name: mongo-pod