apiVersion: v1
kind: Service
metadata:
    name: mssql-service
    labels:
        nmae: mssql-service
        app: database
spec:
    type: LoadBalancer
    ports:
        - port: 1433
          targetPort: 1433
    selector:
        app: microservice-seguridad
        name: mssql-pod